### ISSUE TITLE
Be clear at README.MD about Docker

### ISSUE THREAD

**Issue by kafeltz** [typicode/json-server#1009]
I want to suggest an idea do let super clear in the README.MD by opening an section with title `Docker` saying at least the need open the server with `--host 0.0.0.0`. It's subtle problem if you forget.

And maybe another item to say is about the --watch with the volume.

**Comment by ernescz** [comment]
Just to make clear for those having the same issue as me and @kafeltz - new data not showing up when saved to the `db.json` file (`--watch` not working basically) when running inside a container:

1. `--host 0.0.0.0` must be used otherwise it'll not work from host machine;
2. Docker volume (not direct mounting of `db.json` file) must be used. 

Here are Dockerfile and `docker-compose.yaml` for someone running in the same problem:

`Dockerfile`
```FROM node:16-alpine3.11
WORKDIR /data
RUN npm install -g json-server
CMD ["json-server", "--watch", "db.json", "--host", "0.0.0.0"]
```

`docker-compose.yaml`
```
version: '3'

services:
  json-server:
    container_name: json-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - Assuming your db.json is located in '/Users/meh/code/data/db.json' (adjust path to the correct one):
      - '/Users/meh/code/data:/data'
    ports:
      - '3000:3000'
```
