### ISSUE TITLE
multiple files with beta 1.0.0v1

### ISSUE THREAD

**Issue by solipsist01** [typicode/json-server#1562]
Do you have an example on how to run more json files with beta 1.0.0v1 ?

The most awesome option would be that you could point it to a directory with json files.
like

test1.json
test2.json

paths would automatically be:
http://localhost:3000/test1
http://localhost:3000/test2

I've read older github issues, and saw that you can also run json-server server.js
except, when i do this it tries to read the JS file as if it were json, 
```

root@debian:/docker/compose/api# docker logs api
undefined:1
var jsonServer  = require('json-server')
^

SyntaxError: Unexpected token v in JSON at position 0
    at JSONFile.parse (<anonymous>)
    at JSONFile.read (file:///usr/local/lib/node_modules/json-server/node_modules/lowdb/lib/adapters/node/DataFile.js:17:31)
    at async Observer.read (file:///usr/local/lib/node_modules/json-server/lib/observer.js:21:22)
    at async Low.read (file:///usr/local/lib/node_modules/json-server/node_modules/lowdb/lib/core/Low.js:16:22)
    at async file:///usr/local/lib/node_modules/json-server/lib/bin.js:114:1

Node.js v18.16.0
undefined:1
var jsonServer  = require('json-server')
^

SyntaxError: Unexpected token v in JSON at position 0
    at JSONFile.parse (<anonymous>)
    at JSONFile.read (file:///usr/local/lib/node_modules/json-server/node_modules/lowdb/lib/adapters/node/DataFile.js:17:31)
    at async Observer.read (file:///usr/local/lib/node_modules/json-server/lib/observer.js:21:22)
    at async Low.read (file:///usr/local/lib/node_modules/json-server/node_modules/lowdb/lib/core/Low.js:16:22)
    at async file:///usr/local/lib/node_modules/json-server/lib/bin.js:114:1

Node.js v18.16.0

```
```

version: '3.5'

services:
  api:
    build .
    container_name: api
    command: npx json-server ./server.js
    ports:
      - 8881:3000
    volumes:
      - /docker/data/api:/app
    networks:
      - ${NETWORK}
    restart: ${RESTARTPOLICY}


networks:
  core:
    name: ${NETWORK}

```

```
FROM node:18.16.0-alpine3.17
RUN mkdir -p /app
WORKDIR /app

RUN npm install -g json-server
RUN mkdir /app/public

EXPOSE 3000
CMD [ "npx", "json-server", "/app/db.json", "--host", "0.0.0.0", "-s", "/app/public"]
```
```

root@debian:/docker/data/api# cat server.js
var jsonServer  = require('json-server')
var server      = jsonServer.create()
var router      = jsonServer.router('./db.js')
var middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)
server.listen(3000, function () {
  console.log('JSON Server is running')
})

```

```
root@debian:/docker/data/api# cat db.js
var firstRoute  = require('./test1.json');
var secondRoute = require('./test2.json');

module.exports = function() {
return {
firstRoute  : firstRoute,
secondRoute : secondRoute,
}
}

```

**Comment by solipsist01** [comment]
i gave up :)
i fixed it with traefik and multiple containers.

```
version: '3'

services:
  traefik:
    container_name: api
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - ${NETWORK}
    restart: ${RESTARTPOLICY}


  apibase:
    image: json-server
    container_name: apibase
    labels:
      - "traefik.http.routers.web1.rule=PathPrefix(`/base`)"
      - "traefik.http.services.web1.loadbalancer.server.port=3000"
    volumes:
      - /docker/data/api/base.json:/app/db.json
    networks:
      - ${NETWORK}
    restart: ${RESTARTPOLICY}


  apitest:
    image: json-server
    container_name: apitest
    labels:
      - "traefik.http.routers.web2.rule=PathPrefix(`/posts`)"
      - "traefik.http.routers.web2.rule=PathPrefix(`/comments`)"
      - "traefik.http.services.web2.loadbalancer.server.port=3000"
    volumes:
      - /docker/data/api/test.json:/app/db.json
    networks:
      - ${NETWORK}
    restart: ${RESTARTPOLICY}


networks:
  core:
    name: ${NETWORK}
```
